### ISSUE TITLE
Create Django project skeleton

### ISSUE THREAD

**Issue by natsteinmetz** [shescoding/projects-platform-backend#1]
Make sure to use Pyenv and Pipenv when installing and setting up.

We want to use the latest Django and Python: 
- Django 3
- Python 3.8.0

Ideally call the project 'projects-platform'.

Update the README with info on how to install Python and Django, pyenv and pipenv, and how to run the development server. 

(See https://hackernoon.com/reaching-python-development-nirvana-bb5692adf30c for info on pyenv and pipenv, and the Django tutorial https://docs.djangoproject.com/en/3.0/intro/tutorial01/  for the Django skeleton)

**Comment by kellim** [comment]
Hi @natsteinmetz I mentioned in Slack I want to work on this. It looks like the latest version of Django is 2.2.6 and Python is now 3.7.5 as of this month so I'm assuming we should use the current latest versions which have slightly changed from the above.

**Comment by natsteinmetz** [comment]
@kellim Sounds good, yes! 😃
